"""add embeddings to document chunks

Revision ID: 324eaa3bd2e5
Revises: 5279cd333dc7
Create Date: 2026-09-13 18:18:29.117939

"""
from typing import Sequence, Union
from pgvector.sqlalchemy import Vector

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '324eaa3bd2e5'
down_revision: Union[str, None] = '5279cd333dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'document_chunks',
        sa.Column('embedding', Vector(1536), nullable=True),
    )
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'embedding')
    # ### end Alembic commands ###
